Repository kubeflow/spark-operator, pull requests merged in 2024-09, with the labels that each got.

#2123 Adding support for setting spark job namespaces to all namespaces
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/spark/rbac.yaml
  charts/spark-operator-chart/templates/spark/serviceaccount.yaml
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/templates/webhook/mutatingwebhookconfiguration.yaml
  charts/spark-operator-chart/templates/webhook/validatingwebhookconfiguration.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/spark/serviceaccount_test.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/mutatingwebhookconfiguration_test.yaml
  charts/spark-operator-chart/tests/webhook/validatingwebhookconfiguration_test.yaml
  cmd/operator/controller/start.go
  cmd/operator/webhook/start.go
  internal/controller/scheduledsparkapplication/event_filter.go
  internal/controller/sparkapplication/event_filter.go
Labels: size/L, lgtm, approved

#2136 Support extended kube-scheduler as batch scheduler
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/controller/rbac.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  examples/spark-pi-kube-scheduler.yaml
  go.mod
  go.sum
  internal/controller/sparkapplication/controller.go
  internal/scheduler/kubescheduler/scheduler.go
  internal/scheduler/kubescheduler/util.go
Labels: size/L, lgtm, approved

#2148 Run e2e tests on Kind
  .github/workflows/integration.yaml
  Makefile
  charts/spark-operator-chart/ci/kind-config.yaml
  test/e2e/suit_test.go
Labels: size/M, lgtm, approved

#2153 Set schedulerName to Yunikorn
  internal/scheduler/yunikorn/scheduler.go
  internal/scheduler/yunikorn/scheduler_test.go
Labels: size/XS, lgtm, approved

#1449 Update who-is-using
  docs/who-is-using.md
Labels: lgtm, approved

#2149 Fix: e2e test failes due to webhook not ready
  test/e2e/sparkapplication_test.go
  test/e2e/suit_test.go
Labels: size/L, lgtm, approved

#2155 Upgrade to Go 1.23.1
  Dockerfile
  go.mod
Labels: size/XS, lgtm, approved

#2154 Upgrade to Spark 3.5.2
  Dockerfile
  config/samples/v1beta1_sparkapplication.yaml
  config/samples/v1beta2_scheduledsparkapplication.yaml
  config/samples/v1beta2_sparkapplication.yaml
  examples/spark-pi-configmap.yaml
  examples/spark-pi-custom-resource.yaml
  examples/spark-pi-dynamic-allocation.yaml
  examples/spark-pi-kube-scheduler.yaml
  examples/spark-pi-python.yaml
  examples/spark-pi-scheduled.yaml
  examples/spark-pi-volcano.yaml
  examples/spark-pi-yunikorn.yaml
  examples/spark-pi.yaml
Labels: size/L, lgtm, approved

#2146 feat: support driver and executor pod use different priority
  api/v1beta2/sparkapplication_types.go
  api/v1beta2/zz_generated.deepcopy.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  internal/webhook/sparkpod_defaulter.go
  internal/webhook/sparkpod_defaulter_test.go
Labels: size/M, lgtm, approved

#2161 Update e2e tests
  .github/workflows/integration.yaml
  examples/spark-pi-configmap.yaml
  examples/spark-pi-custom-resource.yaml
  examples/spark-pi-dynamic-allocation.yaml
  examples/spark-pi-kube-scheduler.yaml
  examples/spark-pi-prometheus.yaml
  examples/spark-pi-python.yaml
  examples/spark-pi-scheduled.yaml
  examples/spark-pi-volcano.yaml
  examples/spark-pi-yunikorn.yaml
  examples/spark-pi.yaml
  test/e2e/sparkapplication_test.go
  test/e2e/suit_test.go
Labels: size/L, lgtm, approved

#2163 fix: webhook not working when settings spark job namespaces to empty
  internal/webhook/sparkpod_defaulter.go
Labels: size/S, lgtm, approved, ok-to-test

#2166 fix: The logger had an odd number of arguments, making it panic
  internal/controller/sparkapplication/driveringress.go
Labels: size/XS, lgtm, approved

#2168 replace datamechanics -> spot.io as adopter (acquisition)
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#2157 Upgrade to Spark 3.5.2(#2012)
  examples/spark-pi-prometheus.yaml
  spark-docker/Dockerfile
Labels: size/S, lgtm, approved, ok-to-test

#2164 Feature: Add pprof endpoint
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/_helpers.tpl
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/controller/service.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/controller/service_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
Labels: size/L, lgtm, approved

#2172 fix the make kind-delete-custer to avoid accidental kubeconfig deletion
  Makefile
Labels: size/XS, lgtm, approved

#2170 Add specific error in log line when failed to create web UI service
  internal/controller/sparkapplication/controller.go
Labels: size/XS, lgtm, approved

#2178 Account for spark.executor.pyspark.memory in Yunikorn gang scheduling
  internal/scheduler/yunikorn/resourceusage/memory.go
  internal/scheduler/yunikorn/scheduler_test.go
Labels: size/M, lgtm, approved

#2165 Fix: spark application does not respect time to live seconds
  examples/spark-pi-ttl.yaml
  internal/controller/sparkapplication/controller.go
  pkg/util/sparkapplication.go
Labels: size/L, lgtm, approved

#2182 Release v2.0.0
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS, lgtm, approved

#2171 FEATURE: build operator image as non-root
  Dockerfile
  cmd/operator/webhook/start.go
Labels: size/S, lgtm, approved

#2187 Update controller RBAC for ConfigMap and PersistentVolumeClaim
  charts/spark-operator-chart/templates/controller/_helpers.tpl
Labels: size/S, lgtm, approved

#2190 Group monthly dependabot updates for gomod
  .github/dependabot.yml
Labels: size/S, lgtm, approved

#2195 Add changelog for v2.0.1 and update README
  CHANGELOG.md
  README.md
  VERSION
Labels: size/M, lgtm, approved

#2191 Add yaml file to create serviceaccount
  config/rbac/spark-application-rbac.yaml
Labels: size/M, lgtm, approved

#2186 FEATURE: add cli argument to modify controller workqueue ratelimiter
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  pkg/util/workqueue.go
Labels: size/M, lgtm, approved

#2201 Fix ingress capability discovery
  cmd/operator/controller/start.go
Labels: size/S, lgtm, approved

#2203 Revert "Group monthly dependabot updates for gomod (#2190)"
  .github/dependabot.yml
Labels: size/S, lgtm, approved
