Repository kubeflow/spark-operator, pull requests merged in 2024-08, with the labels that each got.

#2089 Update workflow and docs for releasing Spark operator
  .github/workflows/integration.yaml
  .github/workflows/push-tag.yaml
  .github/workflows/release-charts.yaml
  .github/workflows/release-docker.yaml
  .github/workflows/release.yaml
  VERSION
  charts/spark-operator-chart/.helmignore
  docs/release.md
Labels: lgtm, approved, size/XL

#2109 Fix broken integration test CI
  .github/workflows/integration.yaml
Labels: size/M, lgtm, approved

#2111 Fix CI: environment variable BRANCH is missed
  .github/workflows/integration.yaml
Labels: size/XS, lgtm, approved

#2110 Cherry pick #2089 #2109 #2111
  .github/workflows/integration.yaml
  .github/workflows/push-tag.yaml
  .github/workflows/release-charts.yaml
  .github/workflows/release-docker.yaml
  .github/workflows/release.yaml
  VERSION
  charts/spark-operator-chart/.helmignore
  docs/release.md
Labels: lgtm, approved, size/XL

#2115 Release v2.0.0-rc.0
  VERSION
Labels: size/XS, lgtm, approved

#2124 Increase frequency for Stale bot
  .github/workflows/stale.yaml
Labels: size/XS, lgtm, approved

#2107 Support gang scheduling with Yunikorn
  cmd/operator/controller/start.go
  examples/spark-pi-yunikorn.yaml
  go.mod
  internal/controller/sparkapplication/controller.go
  internal/scheduler/yunikorn/resourceusage/java.go
  internal/scheduler/yunikorn/resourceusage/java_test.go
  internal/scheduler/yunikorn/resourceusage/memory.go
  internal/scheduler/yunikorn/resourceusage/memory_test.go
  internal/scheduler/yunikorn/resourceusage/resource_usage.go
  internal/scheduler/yunikorn/resourceusage/resource_usage_test.go
  internal/scheduler/yunikorn/scheduler.go
  internal/scheduler/yunikorn/scheduler_test.go
  pkg/util/sparkapplication.go
Labels: lgtm, approved, size/XL

#2119 Update Makefile for building sparkctl
  Makefile
  sparkctl/README.md
  sparkctl/build.sh
Labels: size/L, lgtm, approved

#2128 fix: Add default values for namespaces to match usage descriptions
  cmd/operator/controller/start.go
  cmd/operator/webhook/start.go
Labels: size/S, lgtm, approved

#2135 Fix: Spark role binding did not render properly when setting spark service account name
  charts/spark-operator-chart/templates/spark/_helpers.tpl
  charts/spark-operator-chart/templates/spark/rbac.yaml
  charts/spark-operator-chart/tests/spark/rbac_test.yaml
Labels: size/L, lgtm, approved

#2140 Added jacobsalway as a reviewer
  OWNERS
Labels: size/XS, lgtm, approved

#2142 Reintroduce option webhook.enable
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/templates/webhook/mutatingwebhookconfiguration.yaml
  charts/spark-operator-chart/templates/webhook/poddisruptionbudget.yaml
  charts/spark-operator-chart/templates/webhook/rbac.yaml
  charts/spark-operator-chart/templates/webhook/service.yaml
  charts/spark-operator-chart/templates/webhook/serviceaccount.yaml
  charts/spark-operator-chart/templates/webhook/validatingwebhookconfiguration.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/mutatingwebhookconfiguration_test.yaml
  charts/spark-operator-chart/tests/webhook/poddisruptionbudget_test.yaml
  charts/spark-operator-chart/tests/webhook/service_test.yaml
  charts/spark-operator-chart/tests/webhook/validatingwebhookconfiguration_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#2143 Add default batch scheduler argument
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  internal/controller/sparkapplication/controller.go
Labels: size/M, lgtm, approved

#2121 Update release workflow and docs
  .github/workflows/check-release.yaml
  .github/workflows/push-tag.yaml
  .github/workflows/release-docker.yaml
  .github/workflows/release-helm-charts.yaml
  .github/workflows/release.yaml
  docs/release.md
Labels: lgtm, approved, size/XL

#2147 fix: unable to set controller/webhook replicas to zero
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
Labels: size/S, lgtm, approved
