Repository kubeflow/spark-operator, pull requests merged in 2024-06, with the labels that each got.

#2044 Bump appVersion to v1beta2-1.5.0-3.5.0
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS, lgtm, approved

#2045 Add ChenYi015 as spark-operator reviewer
  OWNERS
Labels: size/XS, lgtm, approved

#2059 Update minikube version in CI
  .github/workflows/main.yaml
Labels: size/S, lgtm, approved

#2043 Adding an option to set the priority class for spark-operator pod
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/XS, lgtm, approved

#2058 Support objectSelector on mutating webhook
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/values.yaml
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/L, lgtm, approved

#2066 Modified README.MD as per changes discussed on https://github.com/kubeflow/spark-operator/pull/2062
  README.md
Labels: size/XS, lgtm, approved

#2069 Remove .gitlab-ci.yml
  .gitlab-ci.yml
Labels: size/M, lgtm, approved

#2074 Add code of conduct and update contributor guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: size/S, lgtm, approved
