Repository kubeflow/spark-operator, pull requests merged in 2024-12, with the labels that each got.

#2344 The webhook-key-name command-line param isn't taking effect
  cmd/operator/webhook/start.go
Labels: size/XS, lgtm, approved

#2315 Robustness to driver pod taking time to create
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/controller_test.go
Labels: size/L, lgtm, approved

#2354 Release v2.1.0
  .github/workflows/trivy-image-scanning.yaml
  Makefile
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/controller/serviceaccount.yaml
  charts/spark-operator-chart/templates/spark/serviceaccount.yaml
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/templates/webhook/serviceaccount.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  cmd/operator/main.go
  cmd/operator/webhook/start.go
  cmd/sparkctl/README.md
  cmd/sparkctl/app/client.go
  cmd/sparkctl/app/create.go
  cmd/sparkctl/app/create_test.go
  cmd/sparkctl/app/delete.go
  cmd/sparkctl/app/event.go
  cmd/sparkctl/app/forward.go
  cmd/sparkctl/app/gcs.go
  cmd/sparkctl/app/list.go
  cmd/sparkctl/app/log.go
  cmd/sparkctl/app/root.go
  cmd/sparkctl/app/s3.go
  cmd/sparkctl/app/status.go
  cmd/sparkctl/app/testdata/hadoop-conf/binary.dat
  cmd/sparkctl/app/testdata/hadoop-conf/core-site.xml
  cmd/sparkctl/app/testdata/test-app.yaml
  cmd/sparkctl/app/utils.go
  cmd/sparkctl/main.go
  entrypoint.sh
  go.mod
  go.sum
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/controller_test.go
  internal/controller/sparkapplication/submission.go
  internal/webhook/sparkpod_defaulter.go
  pkg/util/sparkapplication.go
  pkg/util/sparkapplication_test.go
  sparkctl/cmd/utils.go
Labels: lgtm, approved, size/XL

#2355 Add changelog for v2.1.0
  CHANGELOG.md
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/M, lgtm, approved

#2361 Promoted jacobsalway from reviewer to approver
  OWNERS
Labels: size/XS, lgtm, approved
