Repository kubeflow/spark-operator, pull requests merged in 2024-07, with the labels that each got.

#2078 Add PodDisruptionBudget to chart
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/poddisruptionbudget.yaml
  charts/spark-operator-chart/tests/poddisruptionbudget_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/L, lgtm, approved

#2081 Update helm docs
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/L, lgtm, approved

#2073 Add workflow for closing stale issues and PRs
  .github/workflows/stale.yaml
Labels: size/M, lgtm, approved

#2087 Add CHANGELOG.md file and use python script to generate it automatically
  CHANGELOG.md
  hack/generate-changelog.py
Labels: size/L, approved

#2096 Add @ChenYi015 to approvers
  OWNERS
Labels: size/XS, lgtm, approved

#2095 Update Stale bot settings
  .github/workflows/stale.yaml
Labels: size/M, lgtm, approved

#2097 Add Alibaba Cloud to adopters
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#2091 Add topologySpreadConstraints
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/tests/deployment_test.yaml
  charts/spark-operator-chart/tests/poddisruptionbudget_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved
