Repository kubeflow/spark-operator, pull requests merged in 2024-11, with the labels that each got.

#2298 Allow setting automountServiceAccountToken
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/controller/serviceaccount.yaml
  charts/spark-operator-chart/templates/spark/serviceaccount.yaml
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/templates/webhook/serviceaccount.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/S, lgtm, approved

#2306 Fix: executor container security context does not work
  internal/webhook/sparkpod_defaulter.go
Labels: size/XS, lgtm, approved

#2305 Fix: should not add emptyDir sizeLimit conf if it is nil
  internal/controller/sparkapplication/submission.go
Labels: size/S, lgtm, approved

#2282 Allow the Controller and Webhook Containers to run with the securityContext: readOnlyRootfilesystem: true
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#2316 Fix: should not add emptyDir sizeLimit conf on executor pods if it is nil
  internal/controller/sparkapplication/submission.go
Labels: size/S, lgtm, approved

#2320 Bump `volcano.sh/apis` to 1.10.0
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#2311 Truncate UI service name if over 63 characters
  pkg/util/sparkapplication.go
  pkg/util/sparkapplication_test.go
Labels: size/M, lgtm, approved
