Repository kubeflow/spark-operator, pull requests merged in 2024-04, with the labels that each got.

#1946 Allow to set webhook job resource limits (#1429,#1300)
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/webhook-cleanup-job.yaml
  charts/spark-operator-chart/templates/webhook-init-job.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/S, lgtm, approved

#1889 Add PVC permission to Operator role
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/templates/rbac.yaml
Labels: lgtm, approved

#1584 remove unmatched quotes from user-guide.md
  docs/user-guide.md
Labels: lgtm, approved

#1917 BUGFIX: Added cancel method to fix context leak
  sparkctl/cmd/event.go
Labels: lgtm, approved

#1778 README for installing operator using kustomize with custom namespace and service name
  docs/quick-start-guide.md
Labels: lgtm, approved

#1954 upgraded golang and dependencies
  go.mod
  go.sum
  sparkctl/cmd/create.go
  sparkctl/cmd/gcs.go
  sparkctl/cmd/s3.go
Labels: lgtm, approved, size/XXL

#1952 feat: add support for custom service labels
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  examples/spark-pi.yaml
  go.sum
  manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
  pkg/apis/sparkoperator.k8s.io/v1beta2/types.go
  pkg/controller/sparkapplication/sparkapp_util.go
  pkg/controller/sparkapplication/sparkui.go
  pkg/controller/sparkapplication/sparkui_test.go
  test/e2e/basic_test.go
Labels: size/L, lgtm, approved

#1956 Cleanup after golang upgrade
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.rh
  Makefile
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/values.yaml
  go.mod
  hack/api-docs/api-docs-template/placeholder.go
  pkg/apis/sparkoperator.k8s.io/v1beta1/zz_generated.deepcopy.go
  pkg/apis/sparkoperator.k8s.io/v1beta2/defaults_test.go
  pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/sparkapplication/controller.go
  sparkctl/cmd/create.go
  sparkctl/cmd/gcs.go
  sparkctl/cmd/s3.go
Labels: size/L, lgtm, approved

#1884 Chart: add patch permissions for spark operator SA to support spark 3.5.0
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/templates/rbac.yaml
Labels: size/XS, lgtm, approved

#1955 support multiple namespaces
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/templates/spark-rbac.yaml
  charts/spark-operator-chart/templates/spark-serviceaccount.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#1961 fix: add containerPort declaration for webhook in helm chart
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/templates/webhook-service.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/S, lgtm, approved

#1958 Update helm chart README
  .pre-commit-config.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/README.md.gotmpl
Labels: size/L, lgtm, approved

#1964 publish chart independently, incremented both chart and image versions to trigger build of both
  .github/workflows/release.yaml
  charts/spark-operator-chart/Chart.yaml
Labels: size/S, lgtm, approved

#1969 fixed docker image tag and updated chart docs
  .github/workflows/release.yaml
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS, lgtm, approved

#1967 Add some helm chart unit tests and fix spark service account render failure when extra annotations are specified
  Makefile
  charts/spark-operator-chart/.helmignore
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/templates/rbac.yaml
  charts/spark-operator-chart/templates/spark-serviceaccount.yaml
  charts/spark-operator-chart/tests/deployment_test.yaml
  charts/spark-operator-chart/tests/rbac_test.yaml
  charts/spark-operator-chart/tests/serviceaccount_test.yaml
  charts/spark-operator-chart/tests/spark-rbac_test.yaml
  charts/spark-operator-chart/tests/spark-serviceaccount_test.yaml
  charts/spark-operator-chart/tests/webhook-service_test.yaml
  docs/developer-guide.md
Labels: lgtm, approved, size/XL

#1968 chore: remove k8s.io/kubernetes replaces and adapt to v1.29.3 apis
  go.mod
  go.sum
  pkg/controller/sparkapplication/sparkapp_util.go
  pkg/controller/sparkapplication/submission.go
Labels: size/L, lgtm, approved

#1983 fix: upgraded k8s deps
  Makefile
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  go.mod
  go.sum
  hack/api-docs/Dockerfile
  main.go
  pkg/batchscheduler/volcano/volcano_scheduler.go
  pkg/controller/scheduledsparkapplication/controller.go
  pkg/controller/sparkapplication/sparkapp_util.go
  pkg/controller/sparkapplication/submission.go
  pkg/webhook/resourceusage/enforcer.go
Labels: lgtm, approved, size/XXL

#1972 fix: fixed serviceaccount annotations
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
  charts/spark-operator-chart/templates/spark-serviceaccount.yaml
  charts/spark-operator-chart/tests/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#1974 Use Kubeflow Docker Hub for Spark Operator Image
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#1986 fix spark-rbac
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/spark-rbac.yaml
Labels: size/XS, lgtm, approved

#1973 Update spark operator permissions for CRD
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/rbac.yaml
Labels: size/XS, lgtm, approved

#1615 chore: Add Timo to user list
  docs/who-is-using.md
Labels: lgtm, approved

#1992 fix: Update Github workflow to publish Helm charts on chart changes, irrespective of image change
  .github/workflows/release.yaml
Labels: size/M, lgtm, approved

#1995 fix: Removed `publish-image` dependency on publishing the helm chart
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved

#1993 Add emptyDir sizeLimit support for local dirs
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  docs/user-guide.md
  pkg/controller/sparkapplication/submission.go
  pkg/controller/sparkapplication/submission_test.go
Labels: size/M, lgtm, approved

#2003 Fix Docker Hub Credentials in CI
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved
