Repository kubeflow/spark-operator, pull requests merged in 2024-05, with the labels that each got.

#2000 Update Spark Job Namespace docs
  README.md
  docs/quick-start-guide.md
Labels: size/S, lgtm, approved

#2014 Remove outdated PySpark experimental warning in example
  examples/spark-py-pi.yaml
Labels: size/XS, lgtm, approved

#1998 Support exposing extra TCP ports in Spark Driver via K8s Ingress
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml
  pkg/apis/sparkoperator.k8s.io/v1beta2/types.go
  pkg/apis/sparkoperator.k8s.io/v1beta2/zz_generated.deepcopy.go
  pkg/controller/sparkapplication/controller.go
  pkg/controller/sparkapplication/driveringress.go
  pkg/controller/sparkapplication/driveringress_test.go
  pkg/controller/sparkapplication/sparkui.go
  pkg/controller/sparkapplication/sparkui_test.go
Labels: lgtm, approved, size/XXL

#2039 Chart: add POD_NAME env for leader election
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/deployment.yaml
Labels: size/S, lgtm, approved

#2040 :memo: Add Inter&Co to who-is-using.md
  docs/who-is-using.md
Labels: size/XS, lgtm, approved
