Repository kubeflow/spark-operator, pull requests merged in 2024-10, with the labels that each got.

#2197 Update integration test workflow and add golangci lint check
  .github/workflows/integration.yaml
  .golangci.yaml
  Makefile
  api/v1beta1/sparkapplication_types.go
  api/v1beta2/defaults.go
  api/v1beta2/defaults_test.go
  api/v1beta2/doc.go
  api/v1beta2/sparkapplication_types.go
  cmd/operator/controller/start.go
  docs/api-docs.md
  internal/controller/scheduledsparkapplication/controller_test.go
  internal/scheduler/volcano/scheduler_test.go
  internal/scheduler/yunikorn/scheduler.go
  internal/scheduler/yunikorn/scheduler_test.go
  internal/webhook/sparkpod_defaulter.go
  internal/webhook/sparkpod_defaulter_test.go
  sparkctl/cmd/create.go
  sparkctl/cmd/event.go
  sparkctl/cmd/forward.go
  sparkctl/cmd/log.go
  test/e2e/suit_test.go
Labels: size/L, lgtm, approved

#2222 fix: imagePullPolicy was ignored
  internal/controller/sparkapplication/submission.go
Labels: size/M, lgtm, approved

#2223 fix: spark-submission failed due to lack of permission by user `spark`
  Dockerfile
Labels: size/XS, lgtm, approved

#2216 Remove `cap_net_bind_service` from image
  Dockerfile
Labels: size/XS, lgtm, approved

#2235 Add @ImpSy as reviewer
  OWNERS
Labels: size/XS, lgtm, approved

#2232 fix: webhook panics due to logging
  internal/webhook/sparkpod_defaulter.go
Labels: size/S, lgtm, approved

#2234 Add check for generating manifests and code
  .github/workflows/integration.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
Labels: size/M, lgtm, approved

#2233 Release v2.0.2
  .github/workflows/integration.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  VERSION
  api/v1beta1/sparkapplication_types.go
  api/v1beta2/defaults.go
  api/v1beta2/defaults_test.go
  api/v1beta2/doc.go
  api/v1beta2/sparkapplication_types.go
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  go.mod
  go.sum
  internal/controller/scheduledsparkapplication/controller_test.go
  internal/controller/sparkapplication/submission.go
  internal/scheduler/volcano/scheduler_test.go
  internal/scheduler/yunikorn/scheduler.go
  internal/scheduler/yunikorn/scheduler_test.go
  internal/webhook/sparkpod_defaulter.go
  internal/webhook/sparkpod_defaulter_test.go
  pkg/util/workqueue.go
  sparkctl/cmd/create.go
  sparkctl/cmd/event.go
  sparkctl/cmd/forward.go
  sparkctl/cmd/log.go
  test/e2e/suit_test.go
Labels: lgtm, approved, size/XL

#2239 Add changelog for v2.0.2
  CHANGELOG.md
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/M, lgtm, approved

#2181 implement an upper bound limit to the number of tracked executor
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/controller_test.go
  pkg/common/spark.go
  pkg/util/sparkpod.go
  pkg/util/sparkpod_test.go
Labels: size/L, lgtm, approved

#2202 Upgrade to Spark 3.5.3
  Dockerfile
  README.md
  config/samples/v1beta1_sparkapplication.yaml
  config/samples/v1beta2_scheduledsparkapplication.yaml
  config/samples/v1beta2_sparkapplication.yaml
  examples/spark-pi-configmap.yaml
  examples/spark-pi-custom-resource.yaml
  examples/spark-pi-dynamic-allocation.yaml
  examples/spark-pi-kube-scheduler.yaml
  examples/spark-pi-prometheus.yaml
  examples/spark-pi-python.yaml
  examples/spark-pi-scheduled.yaml
  examples/spark-pi-ttl.yaml
  examples/spark-pi-volcano.yaml
  examples/spark-pi-yunikorn.yaml
  examples/spark-pi.yaml
  internal/controller/sparkapplication/controller_test.go
  spark-docker/Dockerfile
Labels: size/L, lgtm, approved

#2242 Minor fixes to e2e test `make` targets
  Makefile
Labels: size/XS, lgtm, approved

#2209 Added off heap memory to calculation for YuniKorn gang scheduling
  internal/scheduler/yunikorn/resourceusage/memory.go
  internal/scheduler/yunikorn/scheduler_test.go
Labels: size/L, lgtm, approved

#2243 remove redundant test.sh file
  internal/controller/sparkapplication/controller_test.go
  test.sh
Labels: size/S, lgtm, approved

#2246 Add permissions to controller serviceaccount to list and watch ingresses
  charts/spark-operator-chart/templates/controller/_helpers.tpl
Labels: size/XS, lgtm, approved

#2256 feat: support archives param for spark-submit
  api/v1beta2/sparkapplication_types.go
  api/v1beta2/zz_generated.deepcopy.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  internal/controller/sparkapplication/submission.go
Labels: size/M, lgtm, approved

#2261 Make sure enable-ui-service flag is set to false when controller.uiService.enable is set to false
  charts/spark-operator-chart/templates/controller/deployment.yaml
Labels: size/XS, lgtm, approved

#2255 `omitempty` corrections
  api/v1beta2/scheduledsparkapplication_types.go
  api/v1beta2/sparkapplication_types.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  internal/controller/scheduledsparkapplication/controller_test.go
  internal/controller/sparkapplication/controller_test.go
Labels: size/M, lgtm, approved

#2263 Add release badge to README
  README.md
  codecov.yaml
Labels: size/S, lgtm, approved

#2266 Run e2e tests with Kubernetes version matrix
  .github/workflows/integration.yaml
  Makefile
  charts/spark-operator-chart/ci/kind-config.yaml
Labels: size/S, lgtm, approved

#2278 Allow --ingress-class-name to be specified in chart
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/S, lgtm, approved

#2241 Fix retries
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/submission.go
  pkg/util/sparkapplication.go
  test/e2e/bad_examples/fail-application.yaml
  test/e2e/bad_examples/fail-submission.yaml
  test/e2e/sparkapplication_test.go
  test/e2e/suit_test.go
Labels: size/L, lgtm, approved

#2265 Update default container security context
  Dockerfile
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#2141 Support pod template for Spark 3.x applications
  Makefile
  api/v1beta2/sparkapplication_types.go
  api/v1beta2/zz_generated.deepcopy.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  examples/spark-pi-pod-template.yaml
  go.mod
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/submission.go
  internal/webhook/sparkapplication_defaulter.go
  internal/webhook/sparkapplication_validator.go
  pkg/common/spark.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, approved, size/XL

#2264 Add workflow for releasing sparkctl binary
  .github/workflows/release.yaml
Labels: size/M, lgtm, approved

#2286 Release v2.1.0-rc.0
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS

#2287 Update issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/L, lgtm, approved
