Repository kubeflow/spark-operator, pull requests merged in 2025-04, with the labels that each got.

#2504 Add changelog for v2.1.1
  CHANGELOG.md
Labels: size/M, lgtm, approved

#2466 Remove sparkctl
  .dockerignore
  .github/workflows/integration.yaml
  .github/workflows/release.yaml
  .gitignore
  .golangci.yaml
  Makefile
  README.md
  cmd/sparkctl/README.md
  cmd/sparkctl/app/client.go
  cmd/sparkctl/app/create.go
  cmd/sparkctl/app/create_test.go
  cmd/sparkctl/app/delete.go
  cmd/sparkctl/app/event.go
  cmd/sparkctl/app/forward.go
  cmd/sparkctl/app/gcs.go
  cmd/sparkctl/app/list.go
  cmd/sparkctl/app/log.go
  cmd/sparkctl/app/root.go
  cmd/sparkctl/app/s3.go
  cmd/sparkctl/app/status.go
  cmd/sparkctl/app/testdata/hadoop-conf/binary.dat
  cmd/sparkctl/app/testdata/hadoop-conf/core-site.xml
  cmd/sparkctl/app/testdata/test-app.yaml
  cmd/sparkctl/app/utils.go
  cmd/sparkctl/main.go
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#2478 Enable the override of MemoryLimit through webhook
  api/v1beta2/sparkapplication_types.go
  api/v1beta2/zz_generated.deepcopy.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  internal/webhook/sparkpod_defaulter.go
  internal/webhook/sparkpod_defaulter_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/L, lgtm, approved

#2506 Remove clientset, informer and listers generated by code-generator
  hack/generate-groups.sh
  hack/update-codegen.sh
  hack/verify-codegen.sh
  internal/webhook/suite_test.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_scheduledsparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_sparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/fake/fake_sparkoperator.k8s.io_client.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/scheduledsparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/sparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta1/sparkoperator.k8s.io_client.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/doc.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/fake/doc.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/fake/fake_scheduledsparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/fake/fake_sparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/fake/fake_sparkoperator.k8s.io_client.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/generated_expansion.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/scheduledsparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/sparkapplication.go
  pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1beta2/sparkoperator.k8s.io_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/interface.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/v1beta1/interface.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/v1beta1/scheduledsparkapplication.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/v1beta1/sparkapplication.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/v1beta2/interface.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/v1beta2/scheduledsparkapplication.go
  pkg/client/informers/externalversions/sparkoperator.k8s.io/v1beta2/sparkapplication.go
  pkg/client/listers/sparkoperator.k8s.io/v1beta1/expansion_generated.go
  pkg/client/listers/sparkoperator.k8s.io/v1beta1/scheduledsparkapplication.go
  pkg/client/listers/sparkoperator.k8s.io/v1beta1/sparkapplication.go
  pkg/client/listers/sparkoperator.k8s.io/v1beta2/expansion_generated.go
  pkg/client/listers/sparkoperator.k8s.io/v1beta2/scheduledsparkapplication.go
  pkg/client/listers/sparkoperator.k8s.io/v1beta2/sparkapplication.go
Labels: lgtm, approved, size/XXL
