Repository kubeflow/spark-operator, pull requests merged in 2025-02, with the labels that each got.

#2412 fix make deploy and install
  Makefile
Labels: size/S, lgtm, approved

#2424 Add helm unittest step to integration test workflow
  .github/workflows/integration.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
Labels: size/M, lgtm, approved

#2423 Add option for disabling leader election
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/templates/controller/rbac.yaml
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/templates/webhook/rbac.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/tests/webhook/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/M, lgtm, approved

#2432 ensure passed context is used
  internal/controller/sparkapplication/controller.go
Labels: size/M, lgtm, approved

#2426 Controller should only be granted event permissions in spark job namespaces
  charts/spark-operator-chart/templates/controller/_helpers.tpl
  charts/spark-operator-chart/templates/controller/rbac.yaml
Labels: size/S, lgtm, approved

#2440 docs: Add information about KEP process
  proposals/README.md
Labels: size/XS, lgtm, approved

#2447 use cmd context in sparkctl
  cmd/sparkctl/app/create.go
  cmd/sparkctl/app/log.go
  cmd/sparkctl/app/root.go
Labels: size/M, lgtm, approved

#2439 Make image optional
  internal/controller/sparkapplication/submission.go
Labels: size/XS, lgtm, approved

#2441 Support non-standard Spark container names
  internal/webhook/sparkpod_defaulter.go
Labels: size/XS, lgtm, approved
