Repository kubeflow/spark-operator, pull requests merged in 2025-01, with the labels that each got.

#2377 Add Ninja Van to adopters
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#2397 Adding seccompProfile RuntimeDefault
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/values.yaml
Labels: size/XS, lgtm, approved

#2403 add an example of using prometheus servlet
  examples/spark-pi-prometheus-servlet.yaml
Labels: size/M, lgtm, approved

#2398 Remove dependency on `k8s.io/kubernetes`
  cmd/sparkctl/app/event.go
  go.mod
  go.sum
  pkg/util/interrupt.go
Labels: size/L, lgtm, approved
