Repository kubeflow/spark-operator, pull requests merged in 2025-03, with the labels that each got.

#2451 specify branch name in chart testing
  .github/workflows/integration.yaml
Labels: size/XS, lgtm, approved

#2450 add support for metrics-job-start-latency-buckets flag in helm
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
Labels: size/XS, lgtm, approved

#2467 change env in executorSecretOption
  internal/controller/sparkapplication/submission.go
  pkg/common/spark.go
Labels: size/XS, lgtm, approved

#2485 Add APRA AMCOS to adopters
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#2481 Release v2.1.1
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS, lgtm, approved

#2484 Deprecating sparkctl
  Makefile
  cmd/sparkctl/README.md
  cmd/sparkctl/main.go
Labels: size/XS, lgtm, approved

#2490 Upgrade to Spark 3.5.5
  Dockerfile
  config/samples/v1beta1_sparkapplication.yaml
  config/samples/v1beta2_scheduledsparkapplication.yaml
  config/samples/v1beta2_sparkapplication.yaml
  examples/spark-pi-configmap.yaml
  examples/spark-pi-custom-resource.yaml
  examples/spark-pi-dynamic-allocation.yaml
  examples/spark-pi-kube-scheduler.yaml
  examples/spark-pi-pod-template.yaml
  examples/spark-pi-prometheus-servlet.yaml
  examples/spark-pi-prometheus.yaml
  examples/spark-pi-python.yaml
  examples/spark-pi-scheduled.yaml
  examples/spark-pi-ttl.yaml
  examples/spark-pi-volcano.yaml
  examples/spark-pi-yunikorn.yaml
  examples/spark-pi.yaml
  spark-docker/Dockerfile
  test/e2e/bad_examples/fail-application.yaml
  test/e2e/bad_examples/fail-submission.yaml
Labels: size/L, lgtm, approved

#2489 fix: add webhook cert validity checking
  pkg/certificate/certificate.go
  pkg/certificate/certificate_test.go
Labels: size/M, lgtm, approved

#2483 Changing image repo from docker.io to ghcr.io
  .github/workflows/integration.yaml
  .github/workflows/release.yaml
  Makefile
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/values.yaml
Labels: size/S, lgtm, approved

#2471 Add timeZone to ScheduledSparkApplication
  api/v1beta2/scheduledsparkapplication_types.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  docs/api-docs.md
  internal/controller/scheduledsparkapplication/controller.go
Labels: size/M, lgtm, approved

#2494 Upgrade Golang to 1.24.1 and golangci-lint to 1.64.8
  Dockerfile
  Makefile
  go.mod
Labels: size/XS, lgtm, approved
