Repository kubeflow/spark-operator, pull requests merged in 2025-05, with the labels that each got.

#2516 Remove v1beta1 API
  PROJECT
  README.md
  api/v1beta1/defaults.go
  api/v1beta1/doc.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/register.go
  api/v1beta1/scheduledsparkapplication_types.go
  api/v1beta1/sparkapplication_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/operator/controller/start.go
  cmd/operator/webhook/start.go
  config/samples/kustomization.yaml
  config/samples/v1beta1_scheduledsparkapplication.yaml
  config/samples/v1beta1_sparkapplication.yaml
  internal/controller/scheduledsparkapplication/suite_test.go
  internal/controller/sparkapplication/suite_test.go
  internal/webhook/suite_test.go
  pkg/certificate/suite_test.go
  test/e2e/suit_test.go
Labels: lgtm, approved, size/XXL

#2521 add unit tests for driver and executor configs
  internal/controller/sparkapplication/submission_test.go
Labels: size/L, lgtm, approved

#2528 Fix typo in github pages
  docs/user-guide.md
Labels: size/XS, lgtm

#2530 Adding securityContext to spark examples
  examples/spark-pi-configmap.yaml
  examples/spark-pi-custom-resource.yaml
  examples/spark-pi-dynamic-allocation.yaml
  examples/spark-pi-kube-scheduler.yaml
  examples/spark-pi-pod-template.yaml
  examples/spark-pi-prometheus-servlet.yaml
  examples/spark-pi-prometheus.yaml
  examples/spark-pi-python.yaml
  examples/spark-pi-scheduled.yaml
  examples/spark-pi-ttl.yaml
  examples/spark-pi-volcano.yaml
  examples/spark-pi-yunikorn.yaml
  examples/spark-pi.yaml
Labels: size/L, lgtm, approved

#2511 Add ShuffleTrackingEnabled to DynamicAllocation struct to allow disabling shuffle tracking
  api/v1beta2/sparkapplication_types.go
  api/v1beta2/zz_generated.deepcopy.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkapplications.yaml
  docs/api-docs.md
  internal/controller/sparkapplication/submission.go
  internal/webhook/sparkapplication_defaulter.go
  pkg/util/sparkapplication.go
  pkg/util/sparkapplication_test.go
Labels: size/L, lgtm, approved

#2532 fix and add back unit tests
  internal/controller/sparkapplication/monitoring_config_test.go
Labels: lgtm, approved, size/XL

#2522 Adding Manabu to the reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#2373 Add support for using cert manager to generate webhook certificates
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/_helpers.tpl
  charts/spark-operator-chart/templates/certmanager/_helpers.tpl
  charts/spark-operator-chart/templates/certmanager/certificate.yaml
  charts/spark-operator-chart/templates/certmanager/issuer.yaml
  charts/spark-operator-chart/templates/webhook/_helpers.tpl
  charts/spark-operator-chart/templates/webhook/deployment.yaml
  charts/spark-operator-chart/templates/webhook/mutatingwebhookconfiguration.yaml
  charts/spark-operator-chart/templates/webhook/validatingwebhookconfiguration.yaml
  charts/spark-operator-chart/tests/certmanager/certificate_test.yaml
  charts/spark-operator-chart/tests/certmanager/issuer_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/webhook/start.go
  pkg/certificate/certificate.go
  pkg/certificate/certificate_test.go
  pkg/common/constants.go
Labels: lgtm, approved, size/XL

#2539 Release v2.2.0-rc.0
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS

#2529 #2525 spark metrics in depends on prometheus
  internal/controller/sparkapplication/monitoring_config.go
  internal/controller/sparkapplication/monitoring_config_test.go
  pkg/util/sparkapplication.go
Labels: size/M, lgtm, approved

#2541 Pass the correct LDFLAGS when building the operator image
  .dockerignore
  .gitignore
  Makefile
Labels: size/M, lgtm, approved

#2545 Release v2.2.0-rc.1
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS
