Repository kubeflow/spark-operator, pull requests merged in 2025-06, with the labels that each got.

#2547 Add changelog for v2.2.0
  CHANGELOG.md
  README.md
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/M, lgtm, approved

#2513 Make default ingress tls and annotations congurable in the helm config
  charts/spark-operator-chart/README.md
  charts/spark-operator-chart/templates/controller/deployment.yaml
  charts/spark-operator-chart/tests/controller/deployment_test.yaml
  charts/spark-operator-chart/values.yaml
  cmd/operator/controller/start.go
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/controller_test.go
  internal/controller/sparkapplication/driveringress.go
  internal/controller/sparkapplication/web_ui.go
Labels: size/L, lgtm, approved

#2551 Get logger from context
  Makefile
  go.mod
  internal/controller/sparkapplication/controller.go
  internal/controller/sparkapplication/driveringress.go
  internal/controller/sparkapplication/driveringress_test.go
  internal/controller/sparkapplication/event_filter.go
  internal/controller/sparkapplication/event_handler.go
  internal/controller/sparkapplication/monitoring_config.go
  internal/controller/sparkapplication/monitoring_config_test.go
  internal/controller/sparkapplication/submission.go
  internal/controller/sparkapplication/web_ui.go
Labels: size/L, lgtm, approved

#2560 Update golangci lint
  .golangci.yaml
  Makefile
  internal/controller/scheduledsparkapplication/controller.go
  internal/controller/sparkapplication/driveringress.go
  internal/controller/sparkapplication/driveringress_test.go
  internal/controller/sparkapplication/submission.go
  internal/scheduler/kubescheduler/scheduler.go
  internal/scheduler/volcano/scheduler.go
  internal/scheduler/volcano/scheduler_test.go
  internal/webhook/sparkpod_defaulter.go
  internal/webhook/sparkpod_defaulter_test.go
  pkg/util/metrics.go
  pkg/util/sparkapplication.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: size/L, lgtm, approved

#2568 Release v2.2.1
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS, lgtm, approved

#2570 Add changelog for v2.2.1
  CHANGELOG.md
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/M, lgtm, approved
