Repository kubeflow/spark-operator, pull requests merged in 2025-07, with the labels that each got.

#2571 chore: Adding OpenSSF Badge
  README.md
Labels: size/XS, lgtm, approved

#2564 upgrade to Spark 4.0.0
  Dockerfile
  config/samples/v1beta2_scheduledsparkapplication.yaml
  config/samples/v1beta2_sparkapplication.yaml
  examples/spark-pi-configmap.yaml
  examples/spark-pi-custom-resource.yaml
  examples/spark-pi-dynamic-allocation.yaml
  examples/spark-pi-kube-scheduler.yaml
  examples/spark-pi-pod-template.yaml
  examples/spark-pi-prometheus-servlet.yaml
  examples/spark-pi-prometheus.yaml
  examples/spark-pi-python.yaml
  examples/spark-pi-scheduled.yaml
  examples/spark-pi-ttl.yaml
  examples/spark-pi-volcano.yaml
  examples/spark-pi-yunikorn.yaml
  examples/spark-pi.yaml
  test/e2e/bad_examples/fail-application.yaml
  test/e2e/bad_examples/fail-submission.yaml
Labels: size/L, lgtm, approved

#2582 Splat recordExecutorEvent args for cleaner event messages
  internal/controller/sparkapplication/controller.go
Labels: size/S, lgtm, approved

#2589 Include pod.Status.Message in recordExecutorEvent
  internal/controller/sparkapplication/controller.go
Labels: size/XS, lgtm, approved

#2593 feat(docs): Guide to report security vulnerabilities
  SECURITY.md
Labels: size/M, lgtm, approved

#2592 Add print columns for Spark Connect
  api/v1alpha1/sparkconnect_types.go
  charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkconnects.yaml
  config/crd/bases/sparkoperator.k8s.io_sparkconnects.yaml
Labels: size/S, lgtm, approved

#2603 Release v2.3.0-rc.0
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/XS

#2605 Grant get/patch permissions for SparkConnect CRD to hook ClusterRole
  charts/spark-operator-chart/templates/hook/cluster_role.yaml
  charts/spark-operator-chart/tests/hook/cluster_role_test.yaml
Labels: size/XS, lgtm, approved

#2614 Add changelog for v2.3.0
  CHANGELOG.md
  README.md
  VERSION
  charts/spark-operator-chart/Chart.yaml
  charts/spark-operator-chart/README.md
Labels: size/M, lgtm, approved

#2616 Grant create events permissions to Controller
  charts/spark-operator-chart/templates/controller/rbac.yaml
Labels: size/XS, lgtm, approved
